### ISSUE TITLE
Add support for 64-bit long integers

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/osc.js#11]
The OSC spec includes an optional long integer type. While JavaScript doesn't natively support integers longer than 57 bits (since they are internally represented as floats), there are libraries out that provide support.

This should be an optional feature, with the user choosing to provide the dependency if needed.

**Comment by colinbdclark** [comment]
colinbdclark/osc.js#19 addresses this issue. It needs to be code reviewed, merged and a few unit tests written for it, but it generally looks like a good approach.

**Comment by jonhallur** [comment]
CasparCG OSC output used the long type. Subscribing.

**Comment by colinbdclark** [comment]
#19 has now been merged into master, and I have written unit tests for this functionality. Once I've had a chance to do some manual testing with the [osc.js examples](https://github.com/colinbdclark/osc.js-examples), I'll cut the 1.2 release.

**Comment by colinbdclark** [comment]
The 1.2.0 release is out. It includes support for int64 arguments. Thanks for the contribution, @egasimus!
