### ISSUE TITLE
Invalid OSC packets when recieving via Serial

### ISSUE THREAD

**Issue by PTS93** [colinbdclark/osc.js#127]
When trying to receive OSC messages via Serial I sometimes get [this ](https://github.com/colinbdclark/osc.js/blob/master/src/osc.js#L920-L921) error thrown. This can easily happen when I have a microcontroller attached to the PC (any Arduino with native USB like a Feather M0, Leonardo or Zero) that is sending messages over Serial without any osc client software attached. Now when you start your application the first message you receive might not be complete (at least thats my assumption as UART does not guarantee messages to arrive complete) and the first char in the header fails the check [here ](https://github.com/colinbdclark/osc.js/blob/master/src/osc.js#L914-L918)and consequently throws the error message.

To test you can use this example: https://github.com/CNMAT/OSC/tree/master/examples/SerialSendMessage

**Comment by colinbdclark** [comment]
Hi @PTS93, can you provide an example of your code that is showing this issue? Thanks!

**Comment by colinbdclark** [comment]
Out of curiosity, are you listening for your Port's <code>error</code> event? [If no listeners are registered for an error event, Node.js' behaviour is to throw an error and terminate the process](https://nodejs.org/api/events.html#events_error_events)—presumably as a way to encourage you to actually handle errors. 

osc.js doesn't attempt to decide for you whether the receipt of malformed messages is important to your application or not, so it will always emit an error event if one is encountered. You're of course free to either handle the error accordingly, or to simply ignore them with a no-op.

Does this address the issue for you, or do you think there's a bug here somewhere that I should look into?

**Comment by PTS93** [comment]
I have not tried that, I was under the impression that errors that are actually thrown as in `throw error` instead of emit I could only handle that globally by listening to the exceptions event?
I will give that a try though. So just
```
serialPort.on("error", function (errorMsg) {

});
```
would work to catch the error?

**Comment by colinbdclark** [comment]
Right, but Ports always try/catch their use of the low-level osc.js API. 

So as described in #30, the low-level API does indeed throw Errors. However, Ports such as your <code>SerialPort</code> [will catch any errors thrown while decoding messages](https://github.com/colinbdclark/osc.js/blob/master/src/osc-transports.js#L76-L87) (by functions such as <code>osc.readPacket</code>), and will emit a corresponding <code>error</code> event.

But, you don't have any listeners registered for the <code>error</code> event. So Node.js' behaviour in that case is to actually throw an Error if no listeners are bound. It will also, if there's no attempt to catch those global errors, log the error and terminate the process.

So yes, if you really want to swallow port errors entirely (is that a good idea in your application?), you can just supply an empty function as you have done above.

**Comment by PTS93** [comment]
Oh no sure I just put it there as an example, the application has yet to be written, this error was just the first thing that I stumbled upon while evaluating the setup :)
Thanks for your help, I don't see any reason to change this behaviour in the library, exactly what one would want. If it shouldn't resolve the issue for some reason I will reopen.

**Comment by colinbdclark** [comment]
Awesome, I'm glad this helped! Good luck with your application and keep me in the loop, I'm always interested in hearing about the projects being made with osc.js!

**Comment by PTS93** [comment]
Sure! Actually far from the first time I used the library. I can mail you some stuff if you're interested in projects using the lib :)
