### ISSUE TITLE
ERR! Unexpected end of JSON input while parsing near '...in-node":"^5.1.0","es'

### ISSUE THREAD

**Issue by Craigson** [colinbdclark/osc.js#128]
Getting the following error trying to install through rpm
```
npm ERR! Unexpected end of JSON input while parsing near '...in-node":"^5.1.0","es'
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/craigpickard/.npm/_logs/2018-08-10T02_21_40_489Z-debug.log
```

**Comment by colinbdclark** [comment]
Hi @Craigson, I'm sorry to hear you're having difficulties. I don't have enough information here to help you debug the issue. Can you provide more detail about how you're trying to install osc.js, in what context, the full error message you received, and examples of your <code>package.json</code> or other details about how your application is set up?

**Comment by Craigson** [comment]
Hey Colin,

Apologies for the useless description of the issue, It was late and I was trying to debug this amongst other things simultaneously.

Npm error log is here: https://gist.github.com/Craigson/a00c82b7173c898fb6b943f577c9cf16

package.json is very simple ( you can see I'm using 'osc-js' instead for now):
```
{
  "name": "controller",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "express": "^4.16.3",
    "osc-js": "^1.2.2",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-scripts": "1.1.4",
    "react-swipe": "^5.1.1",
    "swipe-js-iso": "^2.0.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "nodemon": "^1.18.3"
  }
}

```

I'm on OSX 10.13.2, trying to install the package using NPM.

**Comment by colinbdclark** [comment]
Looks like an upstream issue with Node 10.x and the serialport library. I only formally support the latest LTS release of Node.js because it tends to be more stable over time.

I'll cut an upgrade release, and in the interim you should be able to force the use of serialport version 6.2.2.

**Comment by colinbdclark** [comment]
I've published v2.2.4 with an upgrade to various third party dependencies, including the serialport library. Can you confirm that this version works for you on, @Craigson?

**Comment by Craigson** [comment]
Hey Colin,

Thanks for checking on this so quickly, unfortunately still no dice:

```
24 http fetch GET 200 https://registry.npmjs.org/serialport 22ms (from cache)
25 silly fetchPackageMetaData error for serialport@6.2.2 Unexpected end of JSON input while parsing near '...in-node":"^5.1.0","es'
```

**Comment by colinbdclark** [comment]
Hi @Craigson,

I installed Node.js 10.8.0, which ships with npm 6.2.0, and I can't reproduce the error you're seeing. 

Here's the version of your package.json file that I'm using (with osc.js 2.2.4 instead of the oh-so-originally-named osc-js library):

    {
        "name": "controller",
        "version": "0.1.0",
        "private": true,
        "dependencies": {
            "axios": "^0.18.0",
            "express": "^4.16.3",
            "osc": "2.2.4",
            "react": "^16.4.2",
            "react-dom": "^16.4.2",
            "react-scripts": "1.1.4",
            "react-swipe": "^5.1.1",
            "swipe-js-iso": "^2.0.4"
        },
        "scripts": {
            "start": "react-scripts start",
            "build": "react-scripts build",
            "test": "react-scripts test --env=jsdom",
            "eject": "react-scripts eject"
        },
        "devDependencies": {
            "nodemon": "^1.18.3"
        }
    }

Is it possible that there's something else that is the problem here? Have you tried deleting your <code>node_modules</code> directory and re-running, etc.?

**Comment by colinbdclark** [comment]
Hi @Craigson,

Just to be sure, I installed Node.js 10.8.0, which ships with npm 6.2.0, and I can't reproduce the error you're seeing. 

Here's the version of your package.json file that I'm using (which uses osc.js 2.2.4 instead of the oh-so-originally-named osc-js library):

    {
        "name": "controller",
        "version": "0.1.0",
        "private": true,
        "dependencies": {
            "axios": "^0.18.0",
            "express": "^4.16.3",
            "osc": "2.2.4",
            "react": "^16.4.2",
            "react-dom": "^16.4.2",
            "react-scripts": "1.1.4",
            "react-swipe": "^5.1.1",
            "swipe-js-iso": "^2.0.4"
        },
        "scripts": {
            "start": "react-scripts start",
            "build": "react-scripts build",
            "test": "react-scripts test --env=jsdom",
            "eject": "react-scripts eject"
        },
        "devDependencies": {
            "nodemon": "^1.18.3"
        }
    }

Is it possible that there's something else with your application or configuration that could be the problem here? Have you tried deleting your <code>node_modules</code> directory and re-running npm install, etc.?

**Comment by Craigson** [comment]
Hey @colinbdclark,

Apologies for taking so long to get back to you.  After struggling to resolve this issue, the thing that finally worked for me was `npm cache clean --force`

**Comment by colinbdclark** [comment]
Glad you sorted it out, and thanks for letting me know!

**Comment by Jt-TimSpark** [comment]
Hey guys, I tried to run this command "npm install -g firebase-tools"
but it keeps giving me the err "Unexpected end of JSON input while parsing near '...xamples","test":"tes"

How do I resolve this?

**Comment by colinbdclark** [comment]
Hi @Jt-TimSpark, it sounds like you're having trouble with installing a different library, maybe firebase-tools? Sorry to hear it, that sucks. This is the issue tracker for the osc.js project, for using the Open Sound Control protocol. Perhaps there's a Firebase-related forum or a repository for the firebase-tools project that can help answer your question?

**Comment by Jt-TimSpark** [comment]
Thanks.
Could I get the link to the Firebase-related forum or a repository for the
firebase-tools project?
