### ISSUE TITLE
using osc.js without module?

### ISSUE THREAD

**Issue by erikparr** [colinbdclark/osc.js#133]
I am trying to add osc.js to my THREE.js  project without using modules - possible? I have added osc.js and am adding it to my project via script tags `<script src="js/libs/osc.js"></script>` 

then i add a function from osc.js:
`
var udpPort = new osc.UDPPort({
    // This is the port we're listening on.
    localAddress: "127.0.0.1",
    localPort: 57121,
    // This is where sclang is listening for OSC messages.
    remoteAddress: "127.0.0.1",
    remotePort: 57120,
    metadata: true
});
`

I get the following error: `TypeError: undefined is not a constructor (evaluating 'new osc.UDPPort')`

Unfortunately in my case using modules is not a possibility. Any suggestions much appreciated.

**Comment by colinbdclark** [comment]
Hi @erikparr,

An ordinary web browser doesn't support, unfortunately. There are a few options you could consider if you need to communicate over UDP with something like SuperCollider:

- Create an Electron app, is based on Chrome and can do UDP (but will require your app to be installed on everyone's computer)
- Relay UDP messages to and from WebSockets into the browser

There are examples for both these options in the [osc.js examples repository](https://github.com/colinbdclark/osc.js-examples).

I hope this helps!

**Comment by erikparr** [comment]
Thanks @colinbdclark I am giving electron a try and am able to get a three.js example working fine without modules. Next I tried adding osc.js with script tags the same way as above but I am getting the same error from electron: `TypeError: osc.UDPPort is not a constructor`

So am I able to run osc.js without modules in electron or am I missing something?

Much thanks

**Comment by colinbdclark** [comment]
In Electron, you'll need to use Node.js' module loader to access osc.js' Node-based Ports such as <code>osc.UDPPort</code>, rather than including the browser-based build of osc.js as a script tag in your page's HTML.

So, something like this:

    var osc = require("osc");
    var myPort = new osc.UDPPort({...});

**Comment by erikparr** [comment]
Thanks. It took some additional steps but I finally got it working in Electron using modules.

**Comment by colinbdclark** [comment]
Closing this ticket; it looks like the issue was resolved successfully.
