### ISSUE TITLE
Importing OSC from ES module does not work– update UMD wrapper to latest version

### ISSUE THREAD

**Issue by olange** [colinbdclark/osc.js#137]
I would like to import OSC from a Web Component in a web app (that, in browser), using the [ES module import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) syntax:

```js
import { OSC } from "osc";

const osc = new OSC();
osc.open({ host, port });
```

You would assume I have added the module as dependency of my `package.json` and did run `npm install` to retrieve the `osc-js` package from the NPM registry:

```
  …
  "dependencies": {
    "osc-js": "^2.0.2",
   …
  },
```

The build of OSC version 2.0.2 currently does not support module imports. Its build uses a version
of the UMD wrapper, which contains a common bug, the incorrect detection of browser global in _strict mode_ implied by module imports (see https://github.com/umdjs/umd/pull/125).

I am unfamiliar with the build you're using, but it seems to me, it would a matter of updating the UMD wrapper you're using to the latest version – as the above mentioned UMD issue was fixed and merged on 13.10.2017.

**Comment by olange** [comment]
By the way: may thanks for the `osc-js` library. We're successfully using it in our [`@petitatelier/three-web-components/three-camera`](https://github.com/petitatelier/three-web-components/tree/master/packages/three-camera) web component.

We used following workaround to load OSC:

1. Add a `<script src="../node_modules/osc-js/lib/osc.min.js"></script>` element in the HTML page that bootstraps the web app;
2. Reference `OSC` in global scope with the `self` keyword:

```js
const websocketPlugin = new self.OSC.WebsocketClientPlugin();
const osc = new self.OSC( { plugin: websocketPlugin });
osc.open({ host, port });
``` 
 
However, it would be nice if it could simply be imported by the web component itself, so users won't need to worry about adding (add forgetting to add!) one other `<script src="…">` to every page using the web component.

**Comment by colinbdclark** [comment]
Hi @olange, I think maybe the issue you filed is for a different library? Unfortunately, someone else decided to create a different library with the confusingly similar name <code>osc-js</code>, which, based on the same code you've provided, sounds like the library you're using.

**Comment by olange** [comment]
Hi @colinbdclark, you're right, I apologize. I indeed got confused and the issue I reported was intended for [@adzialocha/osc-js](https://github.com/adzialocha/osc-js) library. I will close this issue and report there.
