### ISSUE TITLE
Send error on Node 0.10.34

### ISSUE THREAD

**Issue by jacoscaz** [colinbdclark/osc.js#15]
Hello Colin.

While experimenting with OSC+Node.js and using your wonderful module I stumbled into the following error: 

```
// This is the generating code. 
// I'm proxying OSC-UDP incoming bundles to OSC-WS clients

oscUdpPort.on('bundle', function (oscBundle) {
    console.log('An OSC bundle just arrived!', oscBundle);
    for (var i = 0; i < oscWsPorts.length; i++) {
      oscWsPorts[i].send(oscBundle);
    }
});
```

```
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:153:14)
    at DeflateRaw.Writable.write (_stream_writable.js:182:12)
    at PerMessageDeflate.compress (/Users/jacopo/Code/bidirectional-osc-test/node_modules/ws/lib/PerMessageDeflate.js:260:17)
    at Sender.applyExtensions (/Users/jacopo/Code/bidirectional-osc-test/node_modules/ws/lib/Sender.js:270:54)
    at /Users/jacopo/Code/bidirectional-osc-test/node_modules/ws/lib/Sender.js:116:10
    at Sender.flush (/Users/jacopo/Code/bidirectional-osc-test/node_modules/ws/lib/Sender.js:256:3)
    at Sender.send (/Users/jacopo/Code/bidirectional-osc-test/node_modules/ws/lib/Sender.js:126:8)
    at WebSocket.send (/Users/jacopo/Code/bidirectional-osc-test/node_modules/ws/lib/WebSocket.js:259:18)
    at p.sendRaw (/Users/jacopo/Code/bidirectional-osc-test/node_modules/osc/src/platforms/osc-node.js:245:21)
    at p.send (/Users/jacopo/Code/bidirectional-osc-test/node_modules/osc/src/osc-transports.js:49:22)
```

I've looked a bit into your code and *apparently* traced it to in `src/platforms/osc-node.js`. I went from the following (line 244):

```
this.socket.send(new Uint8Array(encoded), {
```

to the following: 

```
this.socket.send(encoded, {
```

and things started working as expected. 

I'm forking the repo and will try to work on a pull request but I still have to wrap my head around what's going on (I'm not an expert on low-level js and intuition can only take me so far). Any ideas?

**Comment by colinbdclark** [comment]
Hey Jacapo! Thanks for filing the issue and the pull request. This helps a lot.

I'll take a closer look to see what the issue is. It would be great to be able to write a unit test that shows the issue and verifies the fix. Can you show me an example of the data you're sending along via OSC? So when you get the error, what was the message being sent?

Also, any details about what value and type <code>encoded</code> is at line 244 when you get the error would be super helpful. Thanks!

**Comment by jacoscaz** [comment]
Hello Colin.

Unfortunately I don't currently have the means to reproduce the error (I'm
taking a couple of digital-detox days). I can tell you how to reproduce it,
though - just proxy an OSC message from an OSC-UDP port to an OSC-WS one.
I've published what I was working on on GitHub - check
https://github.com/jacoscaz/osc-browser-synth/blob/master/index.js @ line
181.

I think encoded came in as a Buffer even before being passed through
UInt8Array  - don't take my word for this, though, as I'm not that sure.


--

Jacopo Scazzosi
Developer
http://www.jacoscaz.com

**Comment by jacoscaz** [comment]
Hey Colin. I've been back for a while now but forgot to get back at you. Sorry about that. Anything I can help you with?

**Comment by colinbdclark** [comment]
No worries! Sorry for the delay on my end. I've been travelling and haven't had a chance to fix the bug yet, but I think I understand the nature of the issue and your fix appears correct. When I get back home, I'll whip up a unit test and push it.

**Comment by aferriss** [comment]
Thanks for the fix jacoscaz, I was getting the same error and this worked for me as well!

**Comment by colinbdclark** [comment]
Hey @jacoscaz, thanks so much for the fix! I've pushed it to master and will cut a 1.0.5 release shortly. Sorry for the delay looking into this; I really appreciate your help.

**Comment by jacoscaz** [comment]
No worries! I'm excited!  My first proper contribution to another's work..
:)
