### ISSUE TITLE
Can't receive data from multiple UDPPort instances in Node

### ISSUE THREAD

**Issue by tencircles** [colinbdclark/osc.js#151]
I'm having an issue where I'd like to have two node processes running. One of these is the sender and one is the receiver. I'm sure it's something quite easy to solve but I can't seem to make this simple use case work on my local machine. I'm including code sample here, though in the example the ports are running in the same process, I'm seeing the same result, the receiver never gets the messages from the sender.

I've tested with external tools and confirmed that both the sender and the receiver work in isolation, but when running both at the same time, the receiver gets the message.

Any help is greatly appreciated.

```javascript
const osc  = require("osc");

const sender = new osc.UDPPort({
    localAddress : "0.0.0.0",
    localPort    : 57121,
    metadata     : true
});

const receiver = new osc.UDPPort({
    localAddress : "0.0.0.0",
    localPort    : 57122,
    metadata     : true
});

sender.on("ready", () => {
    console.log("sender is ready");
    receiver.open();
});

receiver.on("ready", () => {
    console.log("receiver is ready");
    receiver.on("bundle", () => {
        console.log("this function is never called");
    });
    console.log("sending message");
    sender.send({
        address : "/test",
        args    : [{ type: "s", value: "ok" }]
    }, "127.0.0.1", 57122);
});

sender.on("error", error => {
    console.log("An error occurred: ", error);
});
receiver.on("error", error => {
    console.log("An error occurred: ", error);
});

sender.open();
```

**Comment by colinbdclark** [comment]
Hi @tencircles, sorry to hear about the difficulty. Just from a quick look at your code, it looks like you're listening for incoming OSC bundles (groups of messages), but sending unbundled messages. You can either listen for the <code>message</code> event if you don't plan to use bundles:

    receiver.on("message", () => {
        console.log("this function will be called");
    });
    
...or [send bundles](https://github.com/colinbdclark/osc.js#bundles) instead and leave your receiver code the same.

It looks like the UDPPort documentation is confusing in exactly this way, I'll update it accordingly.

I hope this helps!

**Comment by tencircles** [comment]
Makes perfect sense. Sorry for the trouble, and thanks for the help!
