### ISSUE TITLE
Send automated/gradual OSC message

### ISSUE THREAD

**Issue by jellohouse** [colinbdclark/osc.js#183]
Hi, I want to send an "automated" osc message. For example I would like to gradually increase the opacity of a video in Resolume over an interval of 2 seconds. So at time 0 the opacity is 0.0, and at time 2 seconds the opacity is 1.0.

I know I could try to send an OSC message every 100 milliseconds or so, and increase the value by a bit every time.
But I'm wondering is there any clean way to do this using some specific function of osc.js?

It would be nice if there was something like a send function, but with a range for the value and a time. e.g. 
`osc.send({
            address: '/video/opacity',
            args: [
                {
                  type: "f",
                  valueStart: 0.0,
                  valueEnd: 1.0,
                  time: 2000,
                }
            ]
        })`

**Comment by colinbdclark** [comment]
Hi @jellohouse, it sounds like you're working on an interesting project! The goal of osc.js is to provide a stable, spec-compliant and relatively low-level API for using Open Sound Control, which is amenable to building other abstractions on top of. For this reason, I'm mindful of not adding extra "application level" features that may require different approaches depending on the nature of the application and what platform it's running on. In the case of your feature, the implementation will differ quite substantially depending on how stable the timing needs to be and whether the sender is running in the browser or in a Node.js process.

While it's probably not something we'd want to add to osc.js itself, I think you'd have no problem building this yourself, and I'm happy to highlight other libraries and tools like this built with osc.js in the project's documentation.

For example, you could create a TimedOSCSender object of some kind, which takes a pre-configured <code>osc.Port</code> object and uses it to send periodic messages. Based on what you're describing, you'd likely want to parameterize the start, end, step size, time interval, and stop time. The challenge will be deciding how accurate a clock you need, and how fast it needs to tick. If you're in the browser, you could look at using <code>requestAnimationFrame</code> to provide accurate timing at frame rate, or if you needed faster or unthrottled timing, you could use the Web Audio API. On the other end of the spectrum, if you just need "sort of" level of accuracy, there's always <code>setInterval</code> in the browser and Node.js.

I hope this helps, and good luck with your project.

**Comment by jellohouse** [comment]
Hi @colinbdclark thanks so much for the advice! I very much appreciate it :)
I'm using the browser version in an Electron app. I will probably first try with the simple `setInterval` method.
And I will let you guys know of any updates here.

**Comment by colinbdclark** [comment]
Awesome, keep me posted on how it goes!
