### ISSUE TITLE
OSC message to MuseScore software

### ISSUE THREAD

**Issue by scoresmexico** [colinbdclark/osc.js#189]
MuseScore is kind of difficult, it only receives UDP binary messages.

What am I doing wrong?

```
var msg = {
        address: "/actions/",
        args: [
            {
                type: "s",
                value: "play"
            }
        ]
    };

    var b = osc.writePacket(msg);

    console.log(b)

    console.log("Sending message", msg.address, msg.args, "to", udpPort.options.remoteAddress + ":" + udpPort.options.remotePort);
    udpPort.send(b,"127.0.0.1",5282);
```
The Uint8Array is the same that is sent with another software called Pure Data and it works there.

When tipping `node . ` in terminal, I get

> Uint8Array(24) [
>    47,  97, 99, 116, 105, 111, 110, 115,
>    47,   0,  0,   0,  44, 115,   0,   0,
>   112, 108, 97, 121,   0,   0,   0,   0
> ]
> Sending message /actions/ [ { type: 's', value: 'play' } ] to 127.0.0.1:5282
> node:events:368
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: The specified packet was not recognized as a valid OSC message or bundle. Packet was: {}
>     at Object.osc.writePacket (/Users/patriciocalatayud/Desktop/p5jsOSC/osc.js-examples-master/send-to-supercollider/node_modules/osc/src/osc.js:988:19)
>     at osc.UDPPort.p.encodeOSC (/Users/patriciocalatayud/Desktop/p5jsOSC/osc.js-examples-master/send-to-supercollider/node_modules/osc/src/osc-transports.js:70:27)
>     at osc.UDPPort.p.send (/Users/patriciocalatayud/Desktop/p5jsOSC/osc.js-examples-master/send-to-supercollider/node_modules/osc/src/osc-transports.js:56:28)
>     at Timeout._onTimeout (/Users/patriciocalatayud/Desktop/p5jsOSC/osc.js-examples-master/send-to-supercollider/index.js:36:13)
>     at listOnTimeout (node:internal/timers:557:17)
>     at processTimers (node:internal/timers:500:7)
> Emitted 'error' event on  instance at:
>     at osc.UDPPort.p.encodeOSC (/Users/patriciocalatayud/Desktop/p5jsOSC/osc.js-examples-master/send-to-supercollider/node_modules/osc/src/osc-transports.js:72:18)
>     at osc.UDPPort.p.send (/Users/patriciocalatayud/Desktop/p5jsOSC/osc.js-examples-master/send-to-supercollider/node_modules/osc/src/osc-transports.js:56:28)
>     [... lines matching original stack trace ...]
>     at processTimers (node:internal/timers:500:7)

**Comment by colinbdclark** [comment]
Hi @scoresmexico, thanks for the example code.

It looks like you're calling the ```send()``` method on a Port, which expects to receive an Object containing your OSC message (i.e. your ```msg``` variable). But you're providing it with raw buffer that you've already encoded by hand.

You can either change your last line to ```udpPort.send(msg, "127.0.0.1", 5282);``` and remove the line where you manually encode the message, or if you have some other reason to want to encode the message by hand first, you could use ```udpPort.sendRaw()``` instead.

Does that help?

**Comment by scoresmexico** [comment]
It works, thanks! 
Kind of, the Uint8Array is only sending the address and not the whole message (sorry if this is a basic mistake, I'm new in this).

```
/actions/ 
Uint8Array(24) [
   47,  97,  99, 116, 105, 111, 110, 115,
   47,   0,   0,   0,  44, 115,   0,   0,
  110, 111, 116, 101,  45,  99,   0,   0
]
```
(got from terminal)

And what I need is 
```
/actions/note-c
47 97 99 116 105 111 110 115 47 110 111 116 101 45 99 0 44 0 0 0
```
(got from Pure Data)

What am I doing wrong?

**Comment by colinbdclark** [comment]
I'm super confused here. From what what I understand from a quick Google, MuseScore's OSC commands don't require any arguments. I think that's what you're saying you want, too. 

So then I'm confused why in your previous example you are sending the second half of address as an OSC argument, instead of simply including the whole path in your address?

If you want to send an OSC message with the address```/actions/note-c``` with no arguments, your message object should look like this:

```
let msg = {
    address: "/actions/note-c"
};
```

Or am I missing something about what you're trying to do?

**Comment by scoresmexico** [comment]
Done, amazing thank you!

Here's the code 

```
var osc = require("osc");

var udpPort = new osc.UDPPort({
    // This is the port we're listening on.
    localAddress: "127.0.0.1",
    localPort: 5283,

    // This is where MuseScore is listening for OSC messages.
    remoteAddress: "127.0.0.1",
    remotePort: 5282,
    metadata: true
});

// Open the socket.
udpPort.open();

// Every second, send an OSC message to MuseScore
setInterval(function() {
    // var a = "/actions/note-c";

    var msg = {
        address: "/actions/note-c",
    };

    var b = osc.writePacket(msg);

    console.log(b)

    console.log("Sending message", msg.address, "to", udpPort.options.remoteAddress + ":" + udpPort.options.remotePort);
    udpPort.sendRaw(b);
}, 1000);
```
In [MuseScore's github](https://github.com/musescore/MuseScore/blob/3.x/mscore/shortcut.cpp#L210) there are all possible OSC messages.

**Comment by colinbdclark** [comment]
Awesome! I'm glad it turned out to be any easy fix. Good luck with your project!
