### ISSUE TITLE
reopen the socket

### ISSUE THREAD

**Issue by micrem73** [colinbdclark/osc.js#20]
Hi,
if a IOS mobile screen goes to sleep, the connection is closed. (this doesn't happen with Chrome on Android).
Would be some way to reconnect the client once the screen wakes?

thanks

michele

**Comment by colinbdclark** [comment]
From what I've read, I think the <code>pageshow</code> event is fired when the screen wakes up again in Safari on iOS. You could register an event handler which would then reconnect to the web socket server. I haven't tried it myself, but it seems like it's worth a try.

**Comment by micrem73** [comment]
thanks. I read also about pageshow, and tried something like:


window.addEventListener("pageshow", function(){
   setTimeout(function(){
            if (primavolta > 0 )  {
             port = new osc.WebSocketPort({
                url: "ws://169.254.14.152:8081"
            });
      }      
      alert (primavolta);
      primavolta=primavolta +1; 
    }, 3000);       
}, false);

primavolta skips the reconnection for the first pageshow occur.
But it doesn't work. Is the wrong way to reconnect?

**Comment by colinbdclark** [comment]
I'm not especially familiar with iOS, so I'm not sure what else to suggest. Did you end up finding any solutions?

**Comment by micrem73** [comment]
unfortunately, no.

**Comment by colinbdclark** [comment]
I'm closing this issue since it doesn't directly relate to osc.js, but if any users in the community are familiar with the larger issue of how to reconnect a Web Socket after an iOS device has gone to sleep and been woken up, please feel free to add your comments here.
