### ISSUE TITLE
Running a UDPPort on a server and relaying to web clients via websocket, possible to send remote info relayed messages?

### ISSUE THREAD

**Issue by gilmoregrills** [colinbdclark/osc.js#213]
Hii,

I'm using a setup similar to the one [here](https://github.com/colinbdclark/osc.js-examples/tree/main/udp-browser), in which OSC messages are received over UDP by a server, and then sent to a web client via a websocket. 

When the server `UDPPort` receives a message, it logs both the message and some information about the remote

```
udpPort.on("message", (oscMsg, timeTag, info) => {
  console.log(
    `Received OSC message via UDP: ${JSON.stringify(oscMsg)}, relaying to WebSocket.`,
  );
  console.log("Remote info is: .", info);
});
```

What I want to do is to somehow forward `info` when relaying the message via websocket, so my web client can assign a name based on the IP the message came from and log it alongside the message received, is that possible? 

If it's not, is it possible to modify `oscMsg` (to add the address/name as an arg) in the above `udpPort.on("message"...`, or in the declaration for my `osc.Relay` later on?

**Comment by colinbdclark** [comment]
Hi @gilmoregrills, good question. If you're using ```osc.Relay```, there's no easy way to modify the message or otherwise relay additional data, unfortunately. It's a pretty rudimentary solution for simple use cases. 

But you can do your own relaying, just by listening to the appropriate events on the ```UDPPort``` and sending the message on to the ```WebSocketPort``` with the additional data you want to include.

I hope this helps!

**Comment by gilmoregrills** [comment]
That was super helpful thank you! I was able to get this working kinda:

```
const wss = new WebSocket.Server({
  port: 8081,
});

wss.on("connection", (socket) => {
  console.log("A WebSocket connection has been established.");
  var socketPort = new osc.WebSocketPort({
    socket: socket,
  });

  udpPort.on("message", (oscMsg, timeTag, info) => {
    console.log(
      `Received OSC message via UDP: ${JSON.stringify(oscMsg)}, redirecting it to WebSocket.`,
    );
    const name = generateName(info.address);
    socketPort.send({
      address: oscMsg.address,
      args: [{ type: "s", value: name }, oscMsg.args],
    });
  });

  // this is what i was doing before
  // var relay = new osc.Relay(udpPort, socketPort, {
  //   raw: true,
  // });
});
```
What's happening now that didn't happen before, is that if a client refreshes their page/otherwise disconnects, the next message that is sent to the server causes an error, because node still runs the `udpPort.on("message")` listener(?) that's calling `socketPort.send()` at the now-disconnected client. 

Is there something I need to do when a socketPort is closed? Am I setting up the `udpPort.on()` in a weird place?

**Comment by gilmoregrills** [comment]
I think I solved this! Possibly in an ugly way:

```
wss.on("connection", (socket) => {
  console.log("A WebSocket connection has been established.");
  var socketPort = new osc.WebSocketPort({
    socket: socket,
  });

  function forwardMessageToWebSocket(oscMsg, timeTag, info) {
    console.log(
      `Received OSC message via UDP: ${JSON.stringify(oscMsg)}, redirecting it to WebSocket.`,
    );
    const name = blah()
    try {
      socketPort.send({
        address: oscMsg.address,
        args: [{ type: "s", value: name }, oscMsg.args],
      });
    } catch (error) {
      console.log(`Error sending OSC message to WebSocket: ${error}`);
      udpPort.removeListener("message", forwardMessageToWebSocket);
      socketPort.close();
    }
  }

  udpPort.on("message", forwardMessageToWebSocket);

...
```

It needs tidying up, but it seems to work!
