### ISSUE TITLE
Please add an example to send OSC messages from a webpage without using python or any langage besides JS

### ISSUE THREAD

**Issue by nesdnuma** [colinbdclark/osc.js#214]
Hello,

I could run the web browser example to receive OSC messages on the browser but I couldn't manage to send messages from a webpage.

Could you please add an example with this configuration?

Actually I am trying to send udp messages to the final destination (udpreceive objet in Max) but as far as I can see it's not possible from a web page currently. am I right?

Thank you.

**Comment by nesdnuma** [comment]
Some examples refer to osc.UDPPort but I can't find the definition of UDPPort in osc.js. It's only defined in osc-chromeapp.js. So, is  it possible to use it in a regular browser and does this line load all the library or only osc.js? `osc = require("osc")`

**Comment by colinbdclark** [comment]
UDP is not available in the browser. The only transport available for browsers is Web Sockets.
