### ISSUE TITLE
serialport is 4 months out of date and broke with the new major release

### ISSUE THREAD

**Issue by egasimus** [colinbdclark/osc.js#32]
perhaps nobody's complained yet but that means osc is presently non-installable. what do we do?

**Comment by egasimus** [comment]
https://github.com/voodootikigod/node-serialport/issues/578

**Comment by colinbdclark** [comment]
Ugh. I think it's probably time to do what I've been pondering for a while, which is to split the <code>osc.SerialPort</code> transport and its dependency on the node-serialport library into a separate "micromodule" that can be used with osc.js.

I've noticed users have had a lot of trouble with the serialport library on certain devices (e.g. the Arduino Yun and Atom Electron). Separating it out for those who need serial port access may make for a better general user experience for those who don't.

**Comment by fivdi** [comment]
@egasimus it's called NAN, not node-nan.

**Comment by egasimus** [comment]
@fivdi correct.

**Comment by colinbdclark** [comment]
I've made an experimental branch where I've removed the Node.js serial transport and put it into a  [separate micromodule](https://github.com/colinbdclark/node-osc.js-serialport). I still want to think this through a bit more carefully, since it will be a significant change for users, and I need to also decide what the best way to maintain symmetry between the <code>osc.SerialPort</code> APIs on Chrome and Node.js.

**Comment by egasimus** [comment]
hey, so a heads up.

so i `npm install` commit `346cfe3` under node 4.1.1; got a `serialport` build fail log again but the lib nonetheless seems to install successfully. i try to talk to a thing over osc/udp (the thing being [a tiny custom sound player written in c using liblo](https://github.com/egasimus/postmelodic/blob/master/src/osc.c)) and it responds like `liblo server error in path <some gibberish characters, but not every time>: Invalid message received`.

anyway i don't even reinstall `osc.js`, just use `n` to switch my system-wide node version to `0.12.7` and hey ho it's working mightily fine off the same checkout, and my sound player is playing sounds like i tell it to. `Invalid message` kind of smells like some #29-related shenanigans since you're talking buffers and typedarrays there, but what do i know really.

**Comment by colinbdclark** [comment]
osc.js v2.0.0 has been released, and includes an upgrade to the latest version of node-serialport, which works with Node 4.x. Updates to other libraries such as ws were also done for Node.js 4.x compatibility, and a bug related to how Node.js Buffers are handled was fixed.

osc.js v2.0.0 has been tested and is working with Node.js 4.x!
