### ISSUE TITLE
Error: bind EACCES

### ISSUE THREAD

**Issue by zaherj** [colinbdclark/osc.js#35]
Hi Guys,

Whenever I try udpPort.open() in a nodejs server side I get the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EACCES
    at errnoException (dgram.js:458:11)
    at dgram.js:211:28
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3

Any ideas on how to solve this?

**Comment by colinbdclark** [comment]
Hi @zaherj! Sorry it's not working for you. Can you provide a bit more information about how you're trying to use osc.js? For example, what port are you trying to listen or send on? 

Is there some sample code you can paste in or a repository I can look at to see the context for the error you're receiving?

**Comment by zaherj** [comment]
Thanks @colinbdclark 

It's now working, I was listen on port 57121 but when I changed it to 3000 it worked.

I am on win10

Regards

Zaher.

**Comment by colinbdclark** [comment]
Great, I'm glad to hear it's working! I'll go ahead and close this issue since it sounds like you're all set.
