### ISSUE TITLE
Error throwing

### ISSUE THREAD

**Issue by nomve** [colinbdclark/osc.js#37]
Hi,

thanks for the nice lib, it's been really helpful. I have a similar issue to #31, where if I receive a "malformed message" an error will be thrown. When I do `oscWebSocket.on("message", cb)` and a message is malformed (for instance missing typeTags) I don't have a way to catch this error. Not sure if this is a major issue when used in a real use case, but currently when I send a malformed message in my unit test, they stop executing completely.

**Comment by colinbdclark** [comment]
Hi @nomve. Thanks for the report. Can you provide a unit test that shows how you're using osc.js to cause this issue? I had hoped I'd caught all of the cases where transports were directly throwing errors instead of emitting the <code>error</code> event.

**Comment by nomve** [comment]
Hi @colinbdclark ,

you did (at least in this case). I didn't register an error callback, so that got rid of the problem. Since I run my tests through Karma, node's EventEmitter is less forgiving then the EventEmitter in the browser bundle, and it rethrows the error without at least one error listener. Thank you for the fast reply.

**Comment by colinbdclark** [comment]
Cool, thanks for the clarification. I'm glad to know it's working for you after all. 

If you have any examples of malformed OSC messages that you're using in your unit tests, I would be happy to see them so that I can flesh out a set of more rigorous malformed message unit tests as part of #4.

**Comment by nomve** [comment]
I would help gladly, but I'm not well familiar with OSC in general. I'm using it to support [tuio2](http://www.tuio.org/?tuio20) which builds a protocol on top of OSC. So in general, I just wanted to test what happens in my library if I get a malformed message, and at that point it started breaking.
