### ISSUE TITLE
Not able to use OSC WebSocketPort inside node-webkit or Atom Electron

### ISSUE THREAD

**Issue by jchavarri** [colinbdclark/osc.js#38]
First of all, thanks for creating osc.js. It's an amazing library, both for its functionality but also as a reference on how to program Javascript modules and develop clean, encapsulated code. 👏

I have successfully configured a project that uses OSC.js in NodeJS and listens to clients over websockets.

However, when embedding these clients into node-webkit or Electron, they make the server crash.

What triggers the crash is the action of sending a message after the websocket client is connected (note that this code works when I run it from Chrome):
```
var port = new osc.WebSocketPort({
    url: "ws://localhost:4001"
})

port.on("ready", function() {
    console.log("ready!!!");
    port.send({
        address: "/subscribe",
        args: ["/mg/lk/hand"]
    });
}); 
```

The error I get from nodeJS when I embed the websocket client in node-webkit is:

```
Error: Can't wrap a non-array-like object as Uint8Array. Object was: "undefined"
    at Object.osc.byteArray (node_modules/osc/src/osc.js:92:19)
    at p.decodeOSC (node_modules/osc/src/osc-transports.js:69:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at WebSocket.<anonymous> (node_modules/osc/src/platforms/osc-node.js:281:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (node_modules/ws/lib/WebSocket.js:816:10)
    at node_modules/ws/lib/Receiver.js:477:18
    at node_modules/ws/lib/Receiver.js:361:7
```

I have tried multiple things: using `require` in node-webkit, using `script` tags, using [`nwglobal`](https://github.com/Mithgol/nwglobal) to wrap objects around...

Any ideas will be very helpful.

I'm using osc.js v2.0.1, and node-webkit v0.12.2.

Thanks

**Comment by colinbdclark** [comment]
Hi @jchavarri, thanks for the report. Do you have a sample node-webkit or Atom Electron application I can take a look at?

**Comment by jchavarri** [comment]
Hi @colinbdclark thanks for the quick answer.

Please find in [this link](http://we.tl/GIZb6XXDi4) a zip file that contains a very basic example. You will need to install node-webkit from its site first.

Once you uncompress the zip file, run:
1. `bower install` from `client` folder
2. `npm install` from `server` folder
3. `node index.js` from `server` folder
4. `<path_to_node_webkit> .` from `client` folder

You will then see the error from the `server` Node console.

Thanks again!

**Comment by colinbdclark** [comment]
It was a fascinating issue to debug. I used Atom Electron rather than node-webkit, but I expect the issues should be the same. osc.js was over-optimistically relying on feature detection to determine if it should use native Node.js <code>Buffer</code>s vs. <code>TypedArrayView</code>s. In Electron, at least, Node.js-style Buffers are present in the browser thread, causing them to be used along with the browser implementation of <code>osc.WebSocketPort</code>. This implementation, in turn, buggily sent the entire Buffer's backing ArrayBuffer to the server, rather than only the bytes that were within "view" of the TypedArrayView. In practice, you'd probably never notice this bug when using standard browser typed arrays, but Electron's use of Node buffers (which allocate an 8k backing buffer regardless of how big the Buffer view is) exposed it.

I'll cut a 2.0.2 release when I've completed fixes for #39, but in the meantime, @jchavarri can you test osc.js' master branch with your application and verify if it fixes the problem for you?

**Comment by jchavarri** [comment]
I can confirm that it works on Electron! :) Nice work!

However, in Node Webkit I still get the other error, you can check it with the same code I sent you before. I think it has to do with the way Node Webkit handles Javascript contexts? Maybe [this article](https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts) helps for clarification.

```
throw new Error("Can't wrap a non-array-like object as Uint8Array. Object was: " +
            ^

Error: Can't wrap a non-array-like object as Uint8Array. Object was: "undefined"
    at Object.osc.byteArray (/Users/javi/Projects/sandbox/oscjs_crash/server/node_modules/osc/src/osc.js:92:19)
    at p.decodeOSC (/Users/javi/Projects/sandbox/oscjs_crash/server/node_modules/osc/src/osc-transports.js:71:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at WebSocket.<anonymous> (/Users/javi/Projects/sandbox/oscjs_crash/server/node_modules/osc/src/platforms/osc-node.js:281:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/Users/javi/Projects/sandbox/oscjs_crash/server/node_modules/ws/lib/WebSocket.js:816:10)
    at /Users/javi/Projects/sandbox/oscjs_crash/server/node_modules/ws/lib/Receiver.js:477:18
    at /Users/javi/Projects/sandbox/oscjs_crash/server/node_modules/ws/lib/Receiver.js:361:7
```

Thanks!

**Comment by colinbdclark** [comment]
Hi again @jchavarri, I tried your sample code with nw.js and the master branch of osc.js and everything worked just fine. The client sent a message, which was correctly received on the server without any errors.

Using osc.js 2.0.1 and looking in the debugger, it was clear that it was a similar issue to the one I found with Electron--osc.js was mistakenly wrapping the encoded message as a <code>Buffer</code> object on the client-side (although nw.js' Buffers appear to be even more rudimentary than in Electron).

I can no longer reproduce the issue you're reporting here. Can you double-check that you were indeed using the master branch of osc.js, and if so can you send along an updated version of your example for me to test with?

**Comment by jchavarri** [comment]
Hi @colinbdclark, thanks for your answer. You are right, I had updated the server code but the client one was not properly updated and pointed to a previous commit . 

So it does work! It was my mistake, sorry about that.

Thanks a lot again for your help and swift answer.

**Comment by colinbdclark** [comment]
No worries! Thanks for confirming that the issue is indeed fixed.

**Comment by KonVas** [comment]
Seems I am experiencing the same issue here. Is there any help? I am getting the crash when accessing my app using my iPhone's (old iOS) currently. Is there something I can add to eliminate such issue (blocking specific iOS) if there is no other way for this? Would that be something that could only be possible at this point in case no other fix is at hand with the issue?

`/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/osc/src/osc.js:101
            throw new Error("Can't wrap a non-array-like object as Uint8Array. Object was: " +
            ^

Error: Can't wrap a non-array-like object as Uint8Array. Object was: "2probe"
    at osc.byteArray (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/osc/src/osc.js:101:19)
    at p.decodeOSC (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/osc/src/osc-transports.js:79:20)
    at osc.WebSocketPort.emit (node:events:513:28)
    at socket.onmessage (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/osc/src/platforms/osc-websocket-client.js:58:18)
    at WebSocket.onMessage (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/Users/konstantinos/Dev/Projects/lick-the-toad/node_modules/ws/lib/receiver.js:446:17)

Node.js v19.0.0`

**Comment by colinbdclark** [comment]
Hi @KonVas, sorry to hear about the difficulty. I'm not sure, based on what you've reported, that this is the same issue—it doesn't sound like you're using Electron or NW.js, right? 

Can you open a new issue with further details about your environment and provide a simplified test case that will help me triage the issue? I'm not sure when I'll have time to look into it but will do my best. Thanks!
