### ISSUE TITLE
Output is unexpected when args is undefined

### ISSUE THREAD

**Issue by Lange** [colinbdclark/osc.js#42]
(This issue was written for v2.0.1, but the described behavior is unchanged in v2.0.2.)

When `metadata` is `false` and `args` is undefined, a single null argument is added to the outgoing OSC message. For example:
```
udpPort.send({
    address: '/test',
});

=> /test   ,N   
```

I believe this is caused by [src/osc.js#L717](https://github.com/colinbdclark/osc.js/blob/2b3d3fa16e99bf936a20e741157f0b89dbd04fb5/src/osc.js#L717). This has caused some commands to a Behringer X32 mixer to unexpectedly fail. To resolve this, I had to explicitly define an empty array of arguments:
```
udpPort.send({
    address: '/test',
    args: []
});

=> /test   ,   
```

When `metadata` is `true`, the library throws an error when `args` is undefined.

```
udpPort.send({
    address: '/test',
});

TypeError: Cannot read property 'buffer' of undefined
    at Object.osc.nativeBuffer (<redacted>\node_modules\osc\src\osc.js:112:60)
    at p.send (<redacted>\node_modules\osc\src\osc-transports.js:49:23)
    at module.exports (<redacted>\extension\osc.js:123:13)
    at module.exports (<redacted>\extension\index.js:64:25)
    <internal application stack frames>
```
[src/osc-transports.js#L49](https://github.com/colinbdclark/osc.js/blob/2b3d3fa16e99bf936a20e741157f0b89dbd04fb5/src/osc-transports.js#L49) [src/osc.js#L112](https://github.com/colinbdclark/osc.js/blob/2b3d3fa16e99bf936a20e741157f0b89dbd04fb5/src/osc.js#L112)

These issues aside, this library is great and did precisely what I needed. Thanks!

**Comment by Lange** [comment]
Coincidentally, attepting to run the "/float/andArray" example in the [Mapping OSC to JS](https://github.com/colinbdclark/osc.js/blob/master/README.md#mapping-osc-to-js) section of the readme causes the same `TypeError: Cannot read property 'buffer' of undefined`, regardless of if `metadata` is `true` or `false`.

**Comment by colinbdclark** [comment]
Thanks for the super detailed report, @Lange. Definitely sounds like a couple of bugs. I'll take a look!

**Comment by colinbdclark** [comment]
This issue was resolved in osc.js version 2.0.3. Thanks again for your help with it, @Lange.

**Comment by Lange** [comment]
Fantastic! It's my pleasure, thanks for authoring and maintaining this lib. :+1: 

[Here's a link to a video](https://youtu.be/dIsUSgY1RgY?t=647) where I talk about my use of this lib at the most recent [Games Done Quick](https://gamesdonequick.com/) event, if you're curious.
