### ISSUE TITLE
Separate transport from parsing ?

### ISSUE THREAD

**Issue by natcl** [colinbdclark/osc.js#44]
Hello,

I'd like to use the osc library with Node-RED.  Node-RED already takes care of the transport mechanisms (UDP, TCP, Serial) Is there an example of using this library without declaring a specific transport or do they always need to be tied together ?
Thanks !

**Comment by colinbdclark** [comment]
Hi @natcl, yes, you can of course use the osc.js low-level API to encode and decode OSC messages and bundles. It's documented here:
https://github.com/colinbdclark/osc.js#the-oscjs-low-level-api

You'll want to use the <code>osc.readPacket()</code> and <code>osc.writePacket()</code> functions to read and write OSC packets, respectively.

https://github.com/colinbdclark/osc.js/blob/master/src/osc.js#L894-L938

**Comment by natcl** [comment]
Many thanks, will give it a go !

**Comment by colinbdclark** [comment]
Just a note for others who stumble across this issue in the future, the documentation for osc.js now includes improved documentation on how to use the low-level API without the transports: https://github.com/colinbdclark/osc.js/blob/a3d3e7665c44cda4f19118e7f39a8953acd4d380/README.md#functions
