### ISSUE TITLE
Expose sender on UDP port

### ISSUE THREAD

**Issue by janslow** [colinbdclark/osc.js#45]
It would be useful if there was some way of exposing the sender information on the OSC `message` event.

The data appears to be lost at the UDP port when the `decodeOSC` method is called in the `data` event (at least for the UDP port).

I expect an easy way would be to modify `decodeOSC` to pass the original data to the `message` event.

Alternatively, it may be worth extracting data like the sender in a standard way across all the transport types, so that it's easy to open a port to send a reply back.

**Comment by colinbdclark** [comment]
Hi @janslow, you're right, it's a big omission from osc.js currently. Not all transports will have any relevant sender data, but for those that do, we really need to expose them. I think we'll need to add an additional argument to the appropriate <code>Port</code> events (<code>"osc"</code>, <code>"message"</code> and <code>"bundle"</code>), which consists of a transport-specific object that can contain sender data. Fortunately, it looks like we should be able to do this as a non-breaking API change.

I am tied up for the next few weeks finishing my thesis, but am happy to look at pull requests if anyone in the community wants to contribute. If not, I'll pick this up in March.

**Comment by janslow** [comment]
I'll have a look into it, as it'd be quite useful for my current project.
