### ISSUE TITLE
Please improve autodetection

### ISSUE THREAD

**Issue by hello-computer** [colinbdclark/osc.js#47]
I have issues with int args.
Made following improvemment

```
// Unsupported, non-API function.
    osc.inferTypeForArgument = function (arg) {
        var type = typeof arg;

        // TODO: This is freaking hideous.
        switch (type) {
            case "boolean":
                return arg ? "T" : "F";
            case "string":
                return "s";
            case "number":
                if (parseInt(Number(arg)) == arg) {
                    return "i";
                } else {
                    return "f";
                }
            case "undefined":
                return "N";
            case "object":
                if (arg === null) {
                    return "N";
                } else if (arg instanceof Uint8Array ||
                    arg instanceof ArrayBuffer) {
                    return "b";
      } else if (typeof arg.high === "number" && typeof arg.low === "number") {
                    return "h";
                }
                break;
        }

        throw new Error("Can't infer OSC argument type for value: " +
            JSON.stringify(arg, null, 2));
    };

```

**Comment by colinbdclark** [comment]
Hi @hello-computer, I appreciate your contribution! Can you please create a pull request with your modifications and provide a bit more detail about the issue you encountered and how your fix addresses it?

It's very difficult to tell, based on this snippet of code, what you've changed and what motivates it.

Thanks very much!

**Comment by colinbdclark** [comment]
After looking at your modification a bit more closely, I think I understand the issue you're facing. 

If you need to send data types with osc.js that don't exist natively in JavaScript (such as Integers), or which are ambiguous with other OSC types (such as MIDI arguments vs. blobs), you'll need to disable type inference and use explicitly-typed messages instead. You can do this by setting the <code>metadata</code> option to <code>true</code>. This is documented here:

https://github.com/colinbdclark/osc.js#options-4

You can supply the <code>metadata</code> option to any <code>osc.Port</code> constructor and to the low-level API functions such as <code>osc.writePacket()</code>. You'll need to specify each argument as an object containing <code>type</code> and <code>value</code> fields. This expanded format is described here:

https://github.com/colinbdclark/osc.js#argument-objects-with-type-metadata

Your fix above will make osc.js' already somewhat shaky type inference system even less stable. This code will always infer that any number with a zero mantissa is a integer, which isn't correct. In JavaScript, all numbers are floating-point numbers. So, with this change, when people try to send messages with numbers like <code>2.0</code>, their argument types will be inferred differently from any other number. You can imagine how it would be confusing for a user to send a message like <code>[2.3, 1.0, 4.4]</code> and have its arguments inferred as OSC types <code>["f", "i", "f"]</code>, yet when they send another, apparently identical message like <code>[2.3, 1.1, 4.4]</code>, the types of their message arguments will suddenly change for no immediately obvious reason.

I have had concerns about the type inference system in osc.js for quite a while (hence the comment), and I will likely disable the feature by default in osc.js 3.0.0 in favour of explicit typing. It's very convenient for users who don't need to send integers, but does cause some extra work (i.e. setting the <code>metadata</code> flag) in case you do.

**Comment by colinbdclark** [comment]
I haven't heard anything further about this issue, so I'm assuming the instructions above addressed the issue you were facing. Please feel free to reopen the issue if there is anything else that comes up regarding this problem.
