### ISSUE TITLE
Only sending over UDP

### ISSUE THREAD

**Issue by bobvanluijt** [colinbdclark/osc.js#50]
Hi all,

The [UDP](https://github.com/colinbdclark/osc.js#udp-in-nodejs) example has two mandatory local properties (localPort and localAddress).

I'm in a situation where I want to send data rather than receive it. Can somebody please explain or provide a simple code snippet for sending data?

Thanks!

**Comment by colinbdclark** [comment]
Hi @bobvanluijt,

There are a few examples of sending data via UDP in the [osc.js examples repository](https://github.com/colinbdclark/osc.js-examples). This one sends OSC messages to SuperCollider:

https://github.com/colinbdclark/osc.js-examples/blob/master/send-to-supercollider/index.js

An osc.js <code>UDPPort</code> is designed to support both sending and receiving messages with a single port. But, if you want, you can also use it for one or the other, in which case you only need to specify appropriate remote or local information. As the documentation says, by default if you omit the local information, osc.js will bind the socket locally <code>127.0.0.1</code> and port <code>57121</code>. 

If you're just sending messages to a single host and not listening to any, you only need to provide the <code>remotePort</code> and <code>remoteAddress</code> options. If you do so, you can omit the second and third arguments to <code>send()</code>:

    var udpPort = osc.UDPPort({
        remoteAddress: "192.168.0.1",
        remotePort: 8088
    });

    udpPort.send({
        address: "/freq",
        args: [440]
    });

If you're sending to different hosts and want to reuse the same <code>Port</code> instance, you don't need to set the options, and can instead pass the address and port as arguments to <code>send()</code>:

    var udpPort = osc.UDPPort();
    udpPort.send({
        address: "/freq",
        args: [440]
    }, "192.168.0.1", 8088);

Does this answer your question?

**Comment by hoosierEE** [comment]
That answered the question for me anyway. Thanks!

**Comment by bobvanluijt** [comment]
Fan-tas-tic, thanks!

Confusion is because the [Readme](https://github.com/colinbdclark/osc.js#udp-in-nodejs) gives the impression that the local settings are mandatory...

Anyway, great work, great lib, thanks :+1:
