### ISSUE TITLE
Update to a newer version of serialport

### ISSUE THREAD

**Issue by Lange** [colinbdclark/osc.js#54]
Currently, this project pins `serialport` to version `2.0.6`, which as far as I can tell cannot be compiled with Node.js v6.

EDIT: According to the [serialport changelog](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/master/changelog.md#version-301), experimental support for Node.js v6 was added in version `3.0.1`, with more fixes in `3.1.0`.

**Comment by colinbdclark** [comment]
Yup, it looks like 3.1.2 is the latest and according to their CI, it's passing in Node 6. I'll aim to upgrade, test, and cut a maintenance release. Thanks for pointing this out--most of my projects are still pinned to the LTS release of Node, but supporting more recent versions is worthwhile.

**Comment by Lange** [comment]
Thanks so much for the update!

Are you waiting for some more changes to land before publishing the new version to npm?

**Comment by colinbdclark** [comment]
Yep, sorry for the delay. I've just pushed some fixes for #58 that I want to run through the full QA cycle, and then I'll cut 2.1.0 hopefully tonight.

**Comment by colinbdclark** [comment]
The 2.1.0 release is now published to npm. I hope it helps with your project!

**Comment by Lange** [comment]
Great, thanks again!

If you're curious, I'm using it for [Summer Games Done Quick](https://gamesdonequick.com/), which benefits Doctors Without Borders. Your continued work maintaining this library is very appreciated!
