### ISSUE TITLE
Error on sending OSC packet over UDP

### ISSUE THREAD

**Issue by Plastix** [colinbdclark/osc.js#65]
``` JavaScript
var connection = new osc.UDPPort({
        localAddress: LOCAL_IP_ADDRESS,
        localPort: LOACAL_PORT,
        remoteAddress: EXTERNAL_IP_ADDRESS,
        remotePort: EXTERNAL_PORT,
        broadcast: true,
    })

connection.open()

connection.on("ready", () => {
        var message = {address: "/HELO"}

        connection.send(message)
    })
```

This errors at `connection.send`: `dgram.js:257 Uncaught TypeError: First argument must be a buffer or string`

```
dgram.js:257 Uncaught TypeError: First argument must be a buffer or string
sliceBuffer @   dgram.js:257
Socket.send @   dgram.js:312
p.sendRaw   @   osc/src/platforms/osc-node.js:217
p.send  @   osc/src/osc-transports.js:58
connection.on   @   renderer.js:7
```

Any ideas?

I'm running on Node 6.1.0.

**Comment by colinbdclark** [comment]
Which version of Node.js are you using?

**Comment by Plastix** [comment]
Node 6.10. Sorry for not including it.

**Comment by colinbdclark** [comment]
If you register a listener for the <code>error</code> event on your UDPPort, does it fire with any further information? And just to be sure, you're running the latest release of osc.js, right (version 2.1.0)?

**Comment by Plastix** [comment]
It isn't firing any other information. Using latest osc.js: 2.1.0

**Comment by Plastix** [comment]
I am running Electron 1.2.8. Could this be part of it?

**Comment by colinbdclark** [comment]
That seems quite possible, but I don't know. Can you point me to a test case or simplified example of your application that I can try out?

**Comment by Plastix** [comment]
All I'm doing is trying to send an OSC packet over UDP from Electron's `render.js` process. This `render.js` process has all of Node's APIs available but it isn't Node itself.

I did some messing around and it looks like the problem is that `osc.nativeBuffer` isn't returning a Buffer object that the Node UDP socket wants. 

```JavaScript
    osc.nativeBuffer = function (obj) {
        if (osc.isBufferEnv && osc.isNode) {
            return osc.isBuffer(obj) ? obj : new Buffer(obj.buffer ? obj : new Uint8Array(obj));
        }

        return osc.isTypedArrayView(obj) ? obj : new Uint8Array(obj);
    };
```

Turns out `osc.isBufferEnv = true` and `osc.isNode = false` so it isn't returning a buffer. So I think the issue is that Electron isn't showing up as Node when it should be. 

```
osc.isNode = osc.isCommonJS && typeof window === "undefined";
```

A quick google search shows this is how to check for electron: https://github.com/xiamx/async/commit/c2942837c41b707da17c96d40dea1417728fe9e7

**Comment by Plastix** [comment]
Since `osc.isBufferEnv` is correct for Electron the fix is probably to change the logic in `nativeBuffer` to `if(osc.isBufferEnv || osc.isNode){...}`

Do you think this will break anything else?

**Comment by colinbdclark** [comment]
Yes, it looks like you've diagnosed the issue exactly right, @Plastix, thanks! Our duck typing is failing in the case of Electron, which (annoyingly) exposes some browser globals within the Node thread and vice versa.

While all the unit tests pass with your pull request, I'm a bit worried that this isn't the most robust approach. We may want to explicitly detect Electron renderer processes as you sugguest; I'll think this through a little bit and hopefully come up a with an easy way to unit test this fix. 

In the meantime, just so I understand, are you using a <code>osc.UDPPort</code> from the Electron main process (e.g. the Node process) or a renderer process (e.g. a <code>BrowserWindow</code> Chromium process)? https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md#quick-start

**Comment by Plastix** [comment]
I'm using a `osc.UDPPort` from the Electron the electron `render.js` script that runs in the browser window. What makes Electron's render process special is that it has access to Node.js modules. So I really am calling into node from the browser.

**Comment by colinbdclark** [comment]
Okay, this makes perfect sense. I'm going to devise a way to run the osc.js test suite in Electron, and then I'll add a specific feature detection case for Electron. Thank you again, @Plastix for all your help in triaging this issue, and I'll try to get you a fix as soon as possible.

**Comment by colinbdclark** [comment]
Hi @Plastix, can you paste an example of how you are loading osc.js in your Electron renderer process? What does the <code>head</code> of your <code>BrowserWindow</code>'s HTML page look like?

**Comment by Plastix** [comment]
I'll write you a sample Electron project when I have access to a computer.
Out of town at the moment.

**Comment by Plastix** [comment]
@colinbdclark Check out https://github.com/Plastix/osc-electron-sample. You're going to need a OSC server running to connect to. All the work happens in `renderer.js`. This is basically the electron quick start repo with OSC imported.

**Comment by colinbdclark** [comment]
Thanks, @Plastix. This is massively helpful. It took me a bit to sort it all out, but I now have a failing test that reproduces the issue you encountered, so now I'll put together a decent fix and cut a new release. I hugely appreciate all your help with this.

**Comment by Plastix** [comment]
@colinbdclark Thank you for all the support! The appreciation is very much mutual.
