### ISSUE TITLE
using osc.js client-dide

### ISSUE THREAD

**Issue by mohithingorani** [colinbdclark/osc.js#70]
after downloading osc.js via `npm install osc`, the osc module gets saved in my node_modules.
However, in the example html code it is included with  ` <script src="bower_components/osc.js/dist/osc-browser.js"></script>`

Am i missing a step here? 
How does one ensure that the library is being served with the rest of my static files when using Node.js?

**Comment by colinbdclark** [comment]
Hi Mohit,

You're right, the documentation is somewhat ambiguous. You can use either npm or Bower (or both) to manage OSC as a dependency. The examples assume that you're using Bower for managing web-tier dependencies and npm for Node modules. However, in the long run I feel that npm is a more viable technology for managing dependencies on both sides of the fence, so you might want to just stick with npm and forgo Bower altogether.

If you just want to follow along with examples, you can do a <code>bower install osc.js</code>. Or, to keep it simpler, you can just refer to the version of osc.js you have installed in your <code>node_modules</code> directory; either way, the <code>dist/</code> folder is the same and contains everything you need for web clients.

In terms of how you manage serving up your dependencies with the rest of your static dependencies using Node.js, that depends a lot on what libraries you're using in Node.js to develop your application. You can find an example of serving up static files to browser clients using Express in the [osc.js examples repository's "browser" example](https://github.com/colinbdclark/osc.js-examples/tree/master/browser).

I hope this helps!

**Comment by mohithingorani** [comment]
Hey @colinbdclark  i just figured it out! I had an incorrectly configured bower. I still have an issue using  the library will email you directly. Thanks!
