### ISSUE TITLE
why start server to send messages ?

### ISSUE THREAD

**Issue by michelson** [colinbdclark/osc.js#88]
Hi @colinbdclark !
thanks for this library, I find it searching for osc clients for node. This work is really good.
I'm just wondering why the client examples are also creating a server ? is possible to create only a client without the need for server? 

I'm working with UDP only

thanks

**Comment by colinbdclark** [comment]
Hi @michelson, I'm glad you like osc.js.

I'm not fully clear on your question, but I think you must be asking about the [browser-based osc.js examples](https://github.com/colinbdclark/osc.js-examples/tree/master/browser)? 

For Node.js or Chrome App API-based applications, there is no need for any kind of server. However, in a standard web browser, it is not possible to send UDP or TCP messages, so a server is required. Some of the examples illustrate the sending of OSC messages over a Web Socket transport, and a server that then proxies these messages to UDP.

Again, put simply, web browsers can't send UDP directly—only Web Sockets. So you need some kind of server to serve up the web pages (due to cross-origin restrictions in web browser) and handle the Web Sockets requests.

I hope this helps!

**Comment by michelson** [comment]
Hi Colin! Thanks for your reply, i'm aware of the client side part, but i'm
only using osc in node ( over udp) . Thing is i need to instantiate several
osc clients to hit others listeners outside app. But it seems that it
create a osc listener server too, so the listener ports init with default
and fail because listener port overlaps . My question is if its possible to
create a node osc client without isntantiate a osc listener?

Best!

**Comment by colinbdclark** [comment]
Hi @michelson, I'm still not 100% sure I fully understand your issue, but it sounds like maybe you have multiple instances of an <code>osc.UDPPort</code>, all of which are binding to the default <code>localPort</code>. Is that correct?

You can configure the remote and local ports and addresses for an <code>osc.UDPPort</code> to whatever you want. Ports are designed as a bidirectional abstraction, even if you don't use them bidirectionally. So if you have port conflicts amongst your instances, just change the defaults as documented here:

https://github.com/colinbdclark/osc.js#udp-in-nodejs

Alternatively, you can create your own Node <code>dgram</code> socket for each remote OSC host you're sending to, and pass the socket as an option when you construct your <code>osc.UDPPort</code>.  This will bypass the default osc.js logic that binds both to local and remote ports.

Does this address your issue?

**Comment by michelson** [comment]
Yup That's is, i need only one direction, remote port only. Without osc
listener. How it can be implemented ?

Are you saying that udp client is always bidireccional or just your design
on osc.UDPPort?

Thanks for your help!

Best

El 28 abr. 2017 5:03 PM, "Colin Clark" <notifications@github.com> escribió:

Hi @michelson <https://github.com/michelson>, I'm still not 100% sure I
fully understand your issue, but it sounds like maybe you have multiple
instances of an osc.UDPPort, all of which are binding to the default
localPort. Is that correct?

You can configure the remote and local ports and addresses for an
osc.UDPPort to whatever you want. Ports are designed as a bidirectional
abstraction, even if you don't use them bidirectionally. So if you have
port conflicts amongst your instances, just change the defaults as
documented here:

https://github.com/colinbdclark/osc.js#udp-in-nodejs

Alternatively, you can create your own Node dgram socket for each remote
OSC host you're sending to, and pass the socket as an option when you
construct your osc.UDPPort. This will bypass the default osc.js logic that
binds both to local and remote ports.

Does this address your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/colinbdclark/osc.js/issues/88#issuecomment-298093710>,
or mute the thread

**Comment by colinbdclark** [comment]
Just specify different port numbers for each Port, using the <code>localPort</code> option:

   var port1 = new osc.UDPPort({localPort: 12345});
   var port2 = new osc.UDPPort({localPort: 45678});

etc.

Or create your own sockets:

   var socket1 = dgram.createSocket('udp4');
   // Set up your socket however you want. See https://nodejs.org/api/dgram.html
  var port1 = new osc.UDPPort({socket: socket1});

UDP sockets in general are bidirectinoal in this sense, though it's not always apparent to you as a user. UDP sockets are always bound to a local port, it's just that the platform will bind to a random port number. An <code>osc.UDPPort</code> makes you specify a port number or socket explicitly.

Colin

**Comment by jean-emmanuel** [comment]
Why not instantiating only one server and specify the target client's address at sending time ?

```
// server
var oscServer = new osc.UDPPort({
    localAddress: "0.0.0.0",
    localPort: 12345
})

// send to 127.0.0.1:4444
oscServer.send({
    address: '/message/for/client/1,
    args: []
}, '127.0.0.1', 4444)

// send to 127.0.0.1:5555
oscServer.send({
    address: '/message/for/client/1,
    args: []
}, '127.0.0.1', 5555)

```

**Comment by colinbdclark** [comment]
Ah! Good point! That should work just fine, and is much more effective, assuming you don't need multiple Port instances for some other reason. Thanks so much, @jean-emmanuel!

**Comment by michelson** [comment]
Yeah , it sounds good. Will be thead safe? I thinking in contexts of
múltiple workers that use port concurrently

**Comment by colinbdclark** [comment]
Node.js is single threaded.

**Comment by michelson** [comment]
I see, thanks for the help!

Best!

**Comment by michelson** [comment]
I've implemented the suggested options and it works just fine.

thanks ! closing now
