### ISSUE TITLE
Consider making Serialport an optionalDependency

### ISSUE THREAD

**Issue by Lange** [colinbdclark/osc.js#96]
Hi!

I use `osc.js` a lot, but I never have used it via `serialport`, only over the network. `serialport` is a native dependency that often needs to be compiled, which makes deploying it more difficult in some situations.

Making it an optionalDependency would reduce the friction to get `osc.js` installed and running in more places.

**Comment by colinbdclark** [comment]
I agree completely. 

And specifying serialport as an optional dependency is only a stopgap—I've been planning for a while to further modularize osc.js so that the various platform-specific transports are fully optional. It's just a matter of finding the time to do so. :)

**Comment by Lange** [comment]
Great!

If it helps motivation, here's two projects I'm working on that have used `osc.js`:
1) https://github.com/Lange/x32-mute-matrix
2) https://twitter.com/VanCamp/status/906757445686628352

Thanks again for creating and maintaining this library!

**Comment by TomKaltz** [comment]
+1

**Comment by natcl** [comment]
As a first step could the osc parsing/construction be handled via a separate non module ?
