### ISSUE TITLE
'undefined' object error when attempting to send over a UDP port

### ISSUE THREAD

**Issue by qbunt** [colinbdclark/osc.js#98]
Looks like I'm getting an error with a very simple implementation inside an Express API. I'm attempting to connect and send over UDP, and I'm getting the following error:

```javascript
/Users/qbunt/git/salesforce-wishingtree-server/node_modules/osc/src/osc-transports.js:46
        this.on("data", this.decodeOSC.bind(this));
                                      ^

TypeError: Cannot read property 'bind' of undefined
    at Object.osc.Port (/Users/qbunt/git/salesforce-wishingtree-server/node_modules/osc/src/osc-transports.js:46:39)
    at Object.osc.UDPPort (/Users/qbunt/git/salesforce-wishingtree-server/node_modules/osc/src/platforms/osc-node.js:142:18)
    at Object.<anonymous> (/Users/qbunt/git/salesforce-wishingtree-server/routes/api.js:6:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

My implementation of your library is the following:
```javascript
var udpPort = osc.UDPPort({
    localAddress: "127.0.0.1",
    localPort: "5000",
})
```

Debugging further, it looks like when the library stands up, and attempts to run this method:
```javascript
osc.Port = function (options) {
        this.options = options || {};
        this.on("data", this.decodeOSC.bind(this));
    };
```
I see the following in my debugger:

![screenshot 2017-10-12 10 45 59](https://user-images.githubusercontent.com/187095/31511272-0e2f1894-af3c-11e7-8e9b-9d4f7f13d792.png)

Happy to help out here with a PR if needed, but wanted to get your input too, seems like an odd error with the level of support there is for UDP.

**Comment by colinbdclark** [comment]
Hi @qbunt,

In the example code you provided, it looks like you're not using the <code>new</code> operator to construct your new <code>osc.UDPPort</code>. Instead, you're calling the constructor as if it were an ordinary function, which will cause its <code>this</code> pointer to be bound to the global object. Hence its inability to resolve the reference to <code>this.decodeOSC</code>.

Does calling <code>new osc.UDPPort()</code> fix your problem?

**Comment by qbunt** [comment]
heh, that was most definitely it. Thanks for the quick response, didn't see the `new` in your docs, but they're most definitely around. UDP is working fine. Thanks again @colinbdclark

**Comment by colinbdclark** [comment]
No problem at all! Glad I could help. Let me know how your project goes, I'm always interested in how people are using osc.js!

**Comment by qbunt** [comment]
This will be for addressable RGB LEDs, sending commands off to an Arduino from an iPad via HTTP. In this case, it's HTTP -> OSC -> UDP -> Arduino -> lights. Pretty simple application, but I'll keep you posted!
